name: 'Teams Workflow Notifications'
author: 'Anthony Kinson'
description: 'A Github Action for sending Workflow run results to Teams'
branding:
  icon: message-square
  color: blue
inputs:
  repo_token:
    description: 'You must manually pass in secrets.GITHUB_TOKEN'
    required: true
  teams_webhook_url:
    description: 'Your teams webhook url'
    required: true
  channel:
    description: 'Override the default channel configured by the TEAMS_WEBHOOK_URL'
    required: false
  name:
    description: 'Override the default name configured by the Teams TEAMS_WEBHOOK_URL'
    required: false
  icon_emoji:
    description: 'Override the default webhook icon with an emoji. Uses emoji code: https://www.webfx.com/tools/emoji-cheat-sheet/'
    required: false
  icon_url:
    description: 'Override the default webhook icon with an image via url.'
    required: false
  include_jobs:
    description: 'Should the teams notification include individual job status and run times'
    required: true
    default: "true"
  include_commit_message:
    description: 'Should the teams notification include the head commit message'
    required: true
    default: "false"
  jobs_to_fetch:
    description: 'Number of jobs to fetch (for workflows with big number of jobs)'
    required: false
    default: '30'
runs:
  using: 'node20'
  main: 'dist/index.js'
